# Generated by Django 5.2.5 on 2025-08-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_project_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(default='', upload_to='content_images/'),
            preserve_default=False,
        ),
    ]
